# permissions for end users to edit tracejobs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: tracejob-editor-role
rules:
- apiGroups:
  - observe.alexeldeib.xyz
  resources:
  - tracejobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - observe.alexeldeib.xyz
  resources:
  - tracejobs/status
  verbs:
  - get
