apiVersion: observe.alexeldeib.xyz/v1alpha1
kind: TraceJob
metadata:
  name: tracejob-sample
spec:
  hostname: aks-main-67151622-vmss000004
  program: -|
    /*
    * biolatency.bt	Block I/O latency as a histogram.
    *			For Linux, uses bpftrace, eBPF.
    *
    * This is a bpftrace version of the bcc tool of the same name.
    *
    * Copyright 2018 Netflix, Inc.
    * Licensed under the Apache License, Version 2.0 (the "License")
    *
    * 13-Sep-2018	Brendan Gregg	Created this.
    */

    BEGIN
    {
      printf("Tracing block device I/O... Hit Ctrl-C to end.\n");
    }

    kprobe:blk_account_io_start
    {
      @start[arg0] = nsecs;
    }

    kprobe:blk_account_io_done
    /@start[arg0]/
    {
      @usecs = hist((nsecs - @start[arg0]) / 1000);
      delete(@start[arg0]);
    }

    END
    {
      clear(@start);
    }
