// +build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
	"k8s.io/apimachinery/pkg/types"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TraceJob) DeepCopyInto(out *TraceJob) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TraceJob.
func (in *TraceJob) DeepCopy() *TraceJob {
	if in == nil {
		return nil
	}
	out := new(TraceJob)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TraceJob) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TraceJobList) DeepCopyInto(out *TraceJobList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]TraceJob, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TraceJobList.
func (in *TraceJobList) DeepCopy() *TraceJobList {
	if in == nil {
		return nil
	}
	out := new(TraceJobList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TraceJobList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TraceJobSpec) DeepCopyInto(out *TraceJobSpec) {
	*out = *in
	if in.ServiceAccount != nil {
		in, out := &in.ServiceAccount, &out.ServiceAccount
		*out = new(string)
		**out = **in
	}
	if in.ImageNameTag != nil {
		in, out := &in.ImageNameTag, &out.ImageNameTag
		*out = new(string)
		**out = **in
	}
	if in.InitImageNameTag != nil {
		in, out := &in.InitImageNameTag, &out.InitImageNameTag
		*out = new(string)
		**out = **in
	}
	if in.Deadline != nil {
		in, out := &in.Deadline, &out.Deadline
		*out = new(int64)
		**out = **in
	}
	if in.DeadlineGracePeriod != nil {
		in, out := &in.DeadlineGracePeriod, &out.DeadlineGracePeriod
		*out = new(int64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TraceJobSpec.
func (in *TraceJobSpec) DeepCopy() *TraceJobSpec {
	if in == nil {
		return nil
	}
	out := new(TraceJobSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TraceJobStatus) DeepCopyInto(out *TraceJobStatus) {
	*out = *in
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(types.UID)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TraceJobStatus.
func (in *TraceJobStatus) DeepCopy() *TraceJobStatus {
	if in == nil {
		return nil
	}
	out := new(TraceJobStatus)
	in.DeepCopyInto(out)
	return out
}
